/*
 * MenuPrincipal.java
 */
package fr.pb.securiteincendie;

import fr.pb.global.Globale;
import java.awt.Color;
import javax.swing.JFrame;
import redis.clients.jedis.Jedis;

/**
 *
 * @author pascal
 */
public class MENUPrincipal extends javax.swing.JFrame {

    private final Jedis jedis;

    /**
     * Creates new form MenuPrincipal
     */
    public MENUPrincipal() {
        initComponents();
        setTitle("Menu principal Redis");
        setLocationRelativeTo(null);
        setVisible(true);
        jedis = new Jedis("172.26.11.34");
        Globale.setConnexionRedis(jedis);

//        Color c = new Color(7D0043);
        //
        this.getContentPane().setBackground(Color.BLACK);

        jButtonLieuLister.setBackground(Color.WHITE);
        jButtonAjouterLieu.setBackground(Color.WHITE);
        jButtonModifierLieu.setBackground(Color.WHITE);
        jButtonSupprimerLieu.setBackground(Color.WHITE);

        jButtonAjouterIncident.setBackground(new Color(238, 118, 0)); // DARKORANGE
        jButtonRUDIncident.setBackground(new Color(238, 118, 0));
        jButtonListerIncidents.setBackground(new Color(238, 118, 0));

        jButtonCRUDCategorie.setBackground(Color.MAGENTA);

        jButtonCRUDCause.setBackground(new Color(173, 255, 47));
//        jButtonCRUDCause.setBorderPainted(true);

        jButtonQuitter.setBackground(Color.RED);

        Globale.setFenetre(this);

    } /// constructeur

    /**
     *
     */
    private void afficherFenetre(JFrame f) {
        f.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAjouterLieu = new javax.swing.JButton();
        jButtonCRUDCause = new javax.swing.JButton();
        jButtonAjouterIncident = new javax.swing.JButton();
        jButtonListerIncidents = new javax.swing.JButton();
        jButtonModifierLieu = new javax.swing.JButton();
        jButtonSupprimerLieu = new javax.swing.JButton();
        jButtonRUDIncident = new javax.swing.JButton();
        jButtonCRUDCategorie = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jButtonCRUDPersonne = new javax.swing.JButton();
        jButtonLieuLister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonAjouterLieu.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jButtonAjouterLieu.setText("Ajouter un lieu");
        jButtonAjouterLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterLieuActionPerformed(evt);
            }
        });

        jButtonCRUDCause.setText("CRUD Cause");
        jButtonCRUDCause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRUDCauseActionPerformed(evt);
            }
        });

        jButtonAjouterIncident.setText("Ajouter un incident");
        jButtonAjouterIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterIncidentActionPerformed(evt);
            }
        });

        jButtonListerIncidents.setText("Lister les incidents");
        jButtonListerIncidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListerIncidentsActionPerformed(evt);
            }
        });

        jButtonModifierLieu.setText("Modifier un lieu");
        jButtonModifierLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierLieuActionPerformed(evt);
            }
        });

        jButtonSupprimerLieu.setText("Supprimer un lieu");
        jButtonSupprimerLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerLieuActionPerformed(evt);
            }
        });

        jButtonRUDIncident.setText("RUD incident");
        jButtonRUDIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUDIncidentActionPerformed(evt);
            }
        });

        jButtonCRUDCategorie.setText("CRUD Catégorie");
        jButtonCRUDCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRUDCategorieActionPerformed(evt);
            }
        });

        jButtonQuitter.setText("Quitter");
        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jButtonCRUDPersonne.setText("CRUD Personne");
        jButtonCRUDPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRUDPersonneActionPerformed(evt);
            }
        });

        jButtonLieuLister.setText("Les lieux");
        jButtonLieuLister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLieuListerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModifierLieu, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jButtonCRUDCause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAjouterIncident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAjouterLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListerIncidents, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jButtonRUDIncident, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSupprimerLieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCRUDCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonQuitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCRUDPersonne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLieuLister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLieuLister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAjouterLieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModifierLieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimerLieu)
                .addGap(30, 30, 30)
                .addComponent(jButtonCRUDCause)
                .addGap(18, 18, 18)
                .addComponent(jButtonCRUDCategorie)
                .addGap(18, 18, 18)
                .addComponent(jButtonCRUDPersonne)
                .addGap(18, 18, 18)
                .addComponent(jButtonAjouterIncident)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListerIncidents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRUDIncident)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonQuitter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterLieuActionPerformed
        //
//        if (al == null) {
//            al = new LieuAjouter();
//            System.out.println("NEW");
//        } else {
//            al.setVisible(true);
//            System.out.println("VISIBLE");
//        }
//        //new AjoutLieu();
//        System.out.println(al);
        afficherFenetre(new LieuAjouter());
    }//GEN-LAST:event_jButtonAjouterLieuActionPerformed

    private void jButtonCRUDCauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRUDCauseActionPerformed
        // 
        //new CauseCRUD();
        afficherFenetre(new CauseCRUD());
    }//GEN-LAST:event_jButtonCRUDCauseActionPerformed

    private void jButtonAjouterIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterIncidentActionPerformed
        // 
//        new IncidentAjout();
        afficherFenetre(new IncidentAjouter());
    }//GEN-LAST:event_jButtonAjouterIncidentActionPerformed

    private void jButtonListerIncidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListerIncidentsActionPerformed
        // 
//        new IncidentLister();
        afficherFenetre(new IncidentLister());
    }//GEN-LAST:event_jButtonListerIncidentsActionPerformed

    private void jButtonSupprimerLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerLieuActionPerformed
        // 
//        new LieuSupprimer();
        afficherFenetre(new LieuSupprimer());
    }//GEN-LAST:event_jButtonSupprimerLieuActionPerformed

    private void jButtonModifierLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierLieuActionPerformed
        //
//        new LieuModifier();
        afficherFenetre(new LieuModifier());
    }//GEN-LAST:event_jButtonModifierLieuActionPerformed

    private void jButtonRUDIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRUDIncidentActionPerformed
        // 
//        new IncidentRUD();
        afficherFenetre(new IncidentRUD());
    }//GEN-LAST:event_jButtonRUDIncidentActionPerformed

    private void jButtonCRUDCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRUDCategorieActionPerformed
        afficherFenetre(new CategorieCRUD());
    }//GEN-LAST:event_jButtonCRUDCategorieActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        // 
        jedis.close();
        Globale.getConnexionRedis().close();
        System.exit(0);
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    private void jButtonCRUDPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRUDPersonneActionPerformed
        // 
        afficherFenetre(new PersonneCRUD());
    }//GEN-LAST:event_jButtonCRUDPersonneActionPerformed

    private void jButtonLieuListerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLieuListerActionPerformed
        afficherFenetre(new LieuLister());
    }//GEN-LAST:event_jButtonLieuListerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        jedis.disconnect();
//        jedis.close();

        RedisConnexion.closeConnection(jedis);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterIncident;
    private javax.swing.JButton jButtonAjouterLieu;
    private javax.swing.JButton jButtonCRUDCategorie;
    private javax.swing.JButton jButtonCRUDCause;
    private javax.swing.JButton jButtonCRUDPersonne;
    private javax.swing.JButton jButtonLieuLister;
    private javax.swing.JButton jButtonListerIncidents;
    private javax.swing.JButton jButtonModifierLieu;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonRUDIncident;
    private javax.swing.JButton jButtonSupprimerLieu;
    // End of variables declaration//GEN-END:variables
}
