/*
 Personnes : MAP {nomPrenom, categorie}
 Categorie : un SET
 */
package fr.pb.securiteincendie;

import fr.pb.global.Globale;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import redis.clients.jedis.Jedis;

/**
 *
 * @author pascal
 */
public class PersonneCRUD extends javax.swing.JFrame {

    private Jedis jedis = Globale.getConnexionRedis();
    private DefaultTableModel idtm;
    private List<Object[]> lPersonnesInit= new ArrayList();
    /**
     * Creates new form PersonneCRUD
     */
    public PersonneCRUD() {
        initComponents();

        remplirTable();
        remplirJCombo();

        setTitle("CRUD Personne");
        setLocationRelativeTo(null);
        setVisible(true);

    } /// Constructeur

    /**
     *
     */
    private void remplirTable() {
        try {

            Object[] tLigne;
            Map<String, String> mapPersonnesInit = jedis.hgetAll("Personnes");
            idtm = (DefaultTableModel) jTablePersonnes.getModel();

            for (int i = idtm.getRowCount() - 1; i >= 0; i--) {
                idtm.removeRow(i);
            }

            String cle;
            String valeur;
            for (Map.Entry<String, String> entry : mapPersonnesInit.entrySet()) {
                cle = entry.getKey(); // Pascal Buguet par exemple
                valeur = entry.getValue(); // Opérateur par exemple
                // Pascal Buguet, Opérateur
                tLigne = new Object[3];
                tLigne[0] = "";
                tLigne[1] = cle;
                tLigne[2] = valeur;
                idtm.addRow(tLigne);
                lPersonnesInit.add(tLigne);
            }

            jLabelMessage.setText("Jusque là tout va bien !!!");

        } catch (Exception e) {
            jLabelMessage.setText(e.getMessage());
        }
    } /// remplirTable

    /**
     *
     */
    private void remplirJCombo() {
        long liTaille = jedis.zcard("Categories");
        Set<String> setCategories = jedis.zrange("Categories", 0, liTaille);
        for (String lsCategorie : setCategories) {
            jComboBoxCategories.addItem(lsCategorie);
        }
    } /// remplirJCombo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldPersonne = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonnes = new javax.swing.JTable();
        jButtonCLS = new javax.swing.JButton();
        jButtonCommit = new javax.swing.JButton();
        jButtonRollback = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCategories = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setText("Prénom et nom");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        jTextFieldPersonne.setText("Tintin");

        jTablePersonnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flag", "Personne", "Catégorie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePersonnes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonnesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonnes);
        if (jTablePersonnes.getColumnModel().getColumnCount() > 0) {
            jTablePersonnes.getColumnModel().getColumn(0).setResizable(false);
        }

        jButtonCLS.setText("CLS");
        jButtonCLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSActionPerformed(evt);
            }
        });

        jButtonCommit.setText("Commit");
        jButtonCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommitActionPerformed(evt);
            }
        });

        jButtonRollback.setText("Rollback");
        jButtonRollback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRollbackActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jLabel1.setText("Catégorie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)
                        .addComponent(jComboBoxCategories, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMessage)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCLS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSupprimer)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCommit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonRollback)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCategories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonCLS)
                    .addComponent(jButtonCommit)
                    .addComponent(jButtonRollback)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        String lsPersonne = jTextFieldPersonne.getText();
        String lsCategorie = jComboBoxCategories.getSelectedItem().toString();

        jLabelMessage.setText("");

        if (lsPersonne.trim().isEmpty()) {
            jLabelMessage.setText("Saisies obligatoires");
        } else {
            String[] tLigne = new String[3];
            tLigne[0] = "+";
            tLigne[1] = lsPersonne;
            tLigne[2] = lsCategorie;
            idtm.addRow(tLigne);
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonCLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSActionPerformed
        //
        jLabelMessage.setText("");
        jTextFieldPersonne.setText("");
    }//GEN-LAST:event_jButtonCLSActionPerformed

    private void jButtonCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommitActionPerformed
        //
        jLabelMessage.setText("");
        Map<String, String> mapPersonne;
        try {
            int liRows = jTablePersonnes.getRowCount();
            String lsFlag;
            String lsPersonne;
            String lsCategorie;

            for (int i = liRows - 1; i >= 0; i--) {
                lsFlag = jTablePersonnes.getValueAt(i, 0).toString();
                lsPersonne = jTablePersonnes.getValueAt(i, 1).toString();
                lsCategorie = jTablePersonnes.getValueAt(i, 2).toString();

                if (lsFlag.equals("+")) {
                    mapPersonne = new LinkedHashMap();
                    mapPersonne.put(lsPersonne, lsCategorie);
                    jedis.hmset("Personnes", mapPersonne);
                    idtm.setValueAt("", i, 0);
                }
                if (lsFlag.equals("-")) {
                    jedis.hdel("Personnes", lsPersonne);
                    idtm.removeRow(i);
                }
                if (lsFlag.equals("v")) {
                    // Suppression puis Ajout
                    jedis.hdel("Personnes",lPersonnesInit.get(i)[1].toString());
                    jedis.hset("Personnes", lsPersonne, lsCategorie);
                            // Il faut avoir gardé la valeur "primitive"
                            //jedis.hmset("Personnels", lsPersonnel);
                    idtm.setValueAt("", i, 0);
                }
            }
            jLabelMessage.setText("Validation définitive OK");
        } catch (Exception e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonCommitActionPerformed

    private void jButtonRollbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRollbackActionPerformed
        //
        remplirTable();

        jLabelMessage.setText("Retour Initial!");

//     
    }//GEN-LAST:event_jButtonRollbackActionPerformed

    private void jTablePersonnesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonnesMouseClicked
        //
        jTextFieldPersonne.setText(jTablePersonnes.getValueAt(jTablePersonnes.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_jTablePersonnesMouseClicked

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        //
        jLabelMessage.setText("");
        int liRow = jTablePersonnes.getSelectedRow();
        if (liRow >= 0) {
            if (jTablePersonnes.getValueAt(liRow, 0).toString().equals("") || jTablePersonnes.getValueAt(liRow, 0).toString().equals("-")) {
                jTablePersonnes.setValueAt("v", liRow, 0);
                jTablePersonnes.setValueAt(jTextFieldPersonne.getText(), liRow, 1);
            }
        } else {
            jLabelMessage.setText("Vous devez sélectionner une ligne !");
        }

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        //
        jLabelMessage.setText("");
        int liRow = jTablePersonnes.getSelectedRow();
        if (liRow >= 0) {
            if (jTablePersonnes.getValueAt(liRow, 0).toString().equals("+")) {
                idtm.removeRow(liRow);
            } else {
                idtm.setValueAt("-", liRow, 0);
            }
        } else {
            jLabelMessage.setText("Vous devez sélectionner une ligne !");
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //
        JFrame f = Globale.getFenetre();
        f.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonneCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonneCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonneCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonneCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonneCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonCLS;
    private javax.swing.JButton jButtonCommit;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRollback;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxCategories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonnes;
    private javax.swing.JTextField jTextFieldPersonne;
    // End of variables declaration//GEN-END:variables
}
